export let INCREMENT = 'INCREMENT';
export let DECREMENT = 'DECREMENT';
export let ASYNC_INCREMENT = 'ASYNC_INCREMENT';
export let CHANGE_THEME = 'CHANGE_THEME';
export let DISABLE_BUTTONS = 'DISABLE_BUTTONS';
export let ENABLE_BUTTONS = 'ENABLE_BUTTONS';